redis:
  db: 0
  addr: '127.0.0.1:6379'
  password: '[password]'

mysql:
  host: '127.0.0.1'
  port: 13306
  database: 'vmimw'
  username: 'root'
  password: 'shadow24'
  charset: 'utf8mb4'
  debug: true
  logLevel: debug
  maxOpenConns: 800
  maxIdleConns: 100
  timeout: '3s'
  parseTime: true

attachment:
  file_path: ''
  file_size: 52428800
  file_ext: 'bmp,ico,psd,jpg,jpeg,png,gif,doc,docx,xls,xlsx,pdf,zip,rar,7z,tz,mp3,mp4,mov,swf,flv,avi,mpg,ogg,wav,flac,ape'


VMIMW:
  name: ""
  version: "v0.0.0"
  addr: 0.0.0.0
  port: 9087
  debug: false
  image: "[url]"

